/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rc2.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 9.21, -1.07]}>
        <primitive object={nodes.spine1} />
        <primitive object={nodes.hipL} />
        <primitive object={nodes.hipR} />
        <skinnedMesh geometry={nodes.Plane001.geometry} material={materials['CVO.001']} skeleton={nodes.Plane001.skeleton} />
        <skinnedMesh geometry={nodes.Plane001_1.geometry} material={materials.CV4} skeleton={nodes.Plane001_1.skeleton} />
        <skinnedMesh geometry={nodes.Plane001_2.geometry} material={materials['CVO.002']} skeleton={nodes.Plane001_2.skeleton} />
      </group>
      <group position={[2.36, 9.75, 15.65]} rotation={[-2.36, 1.21, 2.25]} scale={3.59}>
        <mesh geometry={nodes.Torus003_1.geometry} material={materials['CV5.001']} />
        <mesh geometry={nodes.Torus003_2.geometry} material={materials['CVO.003']} />
        <mesh geometry={nodes.Torus003_3.geometry} material={materials.CV5} />
        <mesh geometry={nodes.Torus003_4.geometry} material={materials['CV4.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/rc2.gltf')
